# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r: devel
cache: packages
warnings_are_errors: false
sudo: true

env:
 global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

r_packages:
- ade4


before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libgsl0-dev bwidget
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc
#  - mkdir ~/.R
#  - Rscript -e 'update.packages(ask = FALSE)'

r:
  - release
  - devel

env:
  - COMPILER=gcc

notifications:
  email:
    recipients:
      - jsigner@gwdg.de
  on_success: change
  on_failure: change
